### ISSUE TITLE
Implement distance sensors for object detection

### ISSUE THREAD

**Issue by madelyntran** [RobotGirls/terkel#99]
Creating code for left and right sensors on the robot. The right sensor will detect if there is an object in the right range if not the left sensor will detect anything in the left range, and if not will default to the middle.

**Comment by madelyntran** [comment]
For now, this will be implemented in team code and possibly implemented into Terkel in the future.

**Comment by danichua** [comment]
Merged into master in pull request
https://github.com/RobotGirls/terkel/pull/102
